version: "3.1"

services:
  db:
    image: mariadb:10.3
    container_name: cooking-app-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cooking-app
      MYSQL_PASSWORD: cooking-app
      MYSQL_DATABASE: cooking-app
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
